"""another migration

Revision ID: 699b16f90d2f
Revises: f6d716e0378d
Create Date: 2025-06-23 21:27:31.282812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699b16f90d2f'
down_revision = 'f6d716e0378d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('minutes_to_complete')
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('minutes_to_complete', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
